/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bookleprojeto;

import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class TelaLogin extends javax.swing.JFrame {

    // Declarando Variaveis
    public static String nomelogado;
    public static String matriculalogado;
    public static String senhalogado;
    public static String tipouser;
    public TelaLogin() {
        initComponents();
    }

    public void acessarSistema() {
        TelaPrincipalBookle telaprin = new TelaPrincipalBookle();
        telaprin.setVisible(true);
    }

    public boolean verificaAutenticacao() {

        boolean acesso = false;

        try {
            ConexaoMysql conectmysql = new ConexaoMysql();
            conectmysql.abrirConexao();
            conectmysql.statement = conectmysql.conexao.createStatement();

            conectmysql.resultset = conectmysql.statement.executeQuery("select * from tbuser");
           
            while (conectmysql.resultset.next()) {
                if ((textfieldNome.getText().equals(conectmysql.resultset.getString("matriculauser"))
                        || textfieldNome.getText().equals(conectmysql.resultset.getString("nomeuser")))
                        && jpasswordField.getText().equals(conectmysql.resultset.getString("senhauser"))) {
                    nomelogado = conectmysql.resultset.getString("nomeuser");
                    matriculalogado = conectmysql.resultset.getString("matriculauser");
                    senhalogado = conectmysql.resultset.getString("senhauser");
                    tipouser =  conectmysql.resultset.getString("permissaouser");
                    acesso = true;
                }
            }

            if (!acesso) {
                JOptionPane.showMessageDialog(null, "Matrícula ou Senha Inválida!", "Acesso Negado", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception erro) {
            System.out.println("Erro Tela Login: " + erro);
        }
        return acesso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textfieldNome = new javax.swing.JTextField();
        jpasswordField = new javax.swing.JPasswordField();
        labelNome = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        buttonSair = new javax.swing.JButton();
        buttonAcessar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelImageLogin = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bookle Login");
        setMinimumSize(new java.awt.Dimension(450, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        textfieldNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textfieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldNomeActionPerformed(evt);
            }
        });
        getContentPane().add(textfieldNome);
        textfieldNome.setBounds(122, 143, 280, 30);

        jpasswordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jpasswordField);
        jpasswordField.setBounds(122, 220, 280, 30);

        labelNome.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelNome.setForeground(new java.awt.Color(0, 102, 153));
        labelNome.setText("Matrícula / Nome Usuário:");
        getContentPane().add(labelNome);
        labelNome.setBounds(122, 117, 260, 24);

        labelPassword.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(0, 102, 153));
        labelPassword.setText("Password:");
        getContentPane().add(labelPassword);
        labelPassword.setBounds(122, 191, 101, 24);

        buttonSair.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookleprojeto/imagensBookle/delete.png"))); // NOI18N
        buttonSair.setText("Sair");
        buttonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSairActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSair);
        buttonSair.setBounds(282, 275, 130, 50);

        buttonAcessar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buttonAcessar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookleprojeto/imagensBookle/accept.png"))); // NOI18N
        buttonAcessar.setText("Entrar");
        buttonAcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAcessarActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAcessar);
        buttonAcessar.setBounds(109, 275, 130, 50);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTitulo.setText("Login Bookle");

        labelImageLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bookleprojeto/imagensBookle/booklelogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(labelImageLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTitulo)
                    .addComponent(labelImageLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 520, 103);

        setSize(new java.awt.Dimension(520, 381));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSairActionPerformed

    private void buttonAcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAcessarActionPerformed
        boolean acesso = false;
        acesso = verificaAutenticacao();
        if (acesso) {
            dispose();
            acessarSistema();
        }

    }//GEN-LAST:event_buttonAcessarActionPerformed

    private void textfieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAcessar;
    private javax.swing.JButton buttonSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jpasswordField;
    private javax.swing.JLabel labelImageLogin;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField textfieldNome;
    // End of variables declaration//GEN-END:variables
}
